#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Alacritty:*:music state=floating border=off

bspc config border_width 2
bspc config window_gap 7
# bspc config left_padding 8
# printf "%s\n" {left,right,bottom}_padding | xargs -I{} bspc config {} 8
# printf "%s\n" {left,right,bottom}_monocle_padding | xargs -I{} bspc config {} -8

bspc config split_ratio 0.5
bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer false

bsp-layout set tall 1
bsp-layout set tiled 2
bsp-layout set tiled 3
bsp-layout set tiled 4
bsp-layout set tiled 5
bsp-layout set tiled 6
bsp-layout set tiled 7
bsp-layout set tiled 8
bsp-layout set tiled 9

pipewire &

redshift -l 59.56639:15.87218 &

feh --no-fehbg --bg-fill "$HOME/Downloads/iceland.png"
xdg-user-dirs-update


picom --experimental-backends --config "$HOME/.config/picom/picom.conf" &
mpd &
/usr/bin/emacs --daemon &
nextcloud --background &

polybar -c "$HOME/.config/polybar/config.ini" main &

sxhkd &
